import type { Product } from "../types/catalog";

export const products: Product[] = [
  {
    id: "mb-heavy-tee",
    name: "Heavy Cotton Tee",
    category: "T-Shirts",
    price: 149,
    compareAt: 199,
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=1000&q=85",
    badge: "BESTSELLER",
    description: "Dense everyday cotton, clean fit and an easy wholesale-friendly price.",
    colors: ["Black", "White", "Rust", "Olive"],
    sizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "mb-oxford-shirt",
    name: "Everyday Oxford Shirt",
    category: "Shirts",
    price: 399,
    compareAt: 499,
    image: "https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=1000&q=85",
    badge: "NEW STOCK",
    description: "A dependable button-down for college, work, travel and daily wear.",
    colors: ["Sky", "White", "Black"],
    sizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "mb-denim",
    name: "Straight Denim",
    category: "Denim",
    price: 699,
    compareAt: 899,
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=1000&q=85",
    badge: "VALUE PICK",
    description: "Straight profile denim with a sturdy hand-feel and an easy everyday wash.",
    colors: ["Indigo", "Black"],
    sizes: ["30", "32", "34", "36", "38"],
  },
  {
    id: "mb-kurta",
    name: "Cotton Kurta",
    category: "Ethnic",
    price: 449,
    image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=1000&q=85",
    badge: "BIHAR EDIT",
    description: "Breathable cotton with a simple silhouette for festive and everyday wear.",
    colors: ["Cream", "White", "Olive"],
    sizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "mb-casual-check",
    name: "Casual Check Shirt",
    category: "Shirts",
    price: 349,
    compareAt: 449,
    image: "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=1000&q=85",
    description: "Soft check texture, relaxed proportions and a repeatable daily uniform.",
    colors: ["Brick", "Forest", "Navy"],
    sizes: ["M", "L", "XL"],
  },
  {
    id: "mb-relaxed-trouser",
    name: "Relaxed Trouser",
    category: "Everyday",
    price: 549,
    compareAt: 699,
    image: "https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=1000&q=85",
    description: "Straight, comfortable trousers built around a no-fuss everyday wardrobe.",
    colors: ["Beige", "Black", "Charcoal"],
    sizes: ["30", "32", "34", "36", "38"],
  },
  {
    id: "mb-polo",
    name: "Piqué Polo",
    category: "T-Shirts",
    price: 299,
    compareAt: 399,
    image: "https://images.unsplash.com/photo-1625910513413-5fc45f18c7bb?auto=format&fit=crop&w=1000&q=85",
    badge: "FAST MOVING",
    description: "Textured polo for the customer who wants one step beyond a basic tee.",
    colors: ["Black", "Bottle", "Stone"],
    sizes: ["M", "L", "XL", "XXL"],
  },
  {
    id: "mb-cotton-pant",
    name: "Cotton Utility Pant",
    category: "Everyday",
    price: 499,
    image: "https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=1000&q=85",
    description: "Practical cotton trouser with the straightforward pricing MAARO is built around.",
    colors: ["Khaki", "Black", "Olive"],
    sizes: ["30", "32", "34", "36"],
  },
];
